### ISSUE TITLE
Allow anonymous check request method bug

### ISSUE THREAD

**Issue by kaancfidan** [kaancfidan/bouncer#22]
**Config:**
``` yaml
routePolicies:
 - path: /**
   allowAnonymous: true
 - path: /**
   methods: [DELETE]
   allowAnonymous: false
```
**Expected behavior:**
Only DELETE requests should be authenticated, all others pass anonymously.

**Actual behavior:**
DELETE also passes anonymously.
